export const EMOJI_MAP: Record<string, string> = {
  food: "🍔",
  coffee: "☕️",
  bakery: "🥐",
  grocery: "🍎",
  local: "🧺",
  fashion: "👗",
  shoes: "👟",
  accessories: "👜",
  beauty: "💄",
  perfume: "🌸",
  hair: "💇‍♀️",
  health: "💊",
  sport: "🏋️‍♂️",
  leisure: "🎲",
  tech: "📱",
  home: "🏡",
  books: "📚",
  flowers: "🌹",
  services: "🛠️",
  pets: "🐶",
  event: "🎉",
  exclusive: "🔑"
};